ISPagrindai/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("users/", include("users.urls")),
    path("music/", include("music.urls")),
    path("playlists/", include("playlists.urls")),
    path("concerts/", include("concerts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

concerts/urls.py
from django.urls import path, include
from . import views

app_name = "concerts"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createConcert, name="createConcert"),
    path("<int:pk>/edit/", views.editConcert, name="editConcert"),
    path("search/", views.searchConcert, name="searchConcert"),
    path("<int:pk>", views.concertDetail, name="concertDetail"),
    path("recommendation/", views.recommendationConcert, name="recommendationConcert"),
]

music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createSong, name="createSong"),
    path("rate/", views.rateSong, name="rateSong"),
    path("edit/", views.editSong, name="editSong"),
    path("play/<int:song_id>", views.playSong, name="playSong"),
    path("similar/", views.similarSongs, name="similarSongs"),
    path("add/<int:song_id>/", views.addToPlaylist, name="addToPlaylist"),
    path("updateHistory/", views.updateListeningHistory, name="updateHistory")
]

playlists/urls.py
from django.urls import path
from . import views

app_name = "playlists"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createPlaylist, name="createPlaylist"),
    path("<int:pk>/", views.PlaylistDetail, name="PlaylistDetail"),
    path("<int:pk>/edit/", views.editPlaylist, name="editPlaylist"),
    path("<int:pk>/delete/", views.deletePlaylist, name="deletePlaylist"),
    path("<int:grojarastis_id>/remove/<int:song_id>/", views.deleteFromPlaylist, name="deleteFromPlaylist"),
    path("<int:pk>/play/", views.playPlaylistSong, name="playPlaylistSong"),
    path("play/<int:pk>/shuffle/", views.playPlaylistShuffle, name="playPlaylistShuffle"
),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:user_id>/", views.userDetail, name="userDetail"),
    path("edit/", views.userEdit, name="userEdit"),
    path("edit/twoFa/<int:enable>", views.twoFa, name="twoFa"),
    path("logout/", views.logoutUser, name="userLogout"),
    path("login/", views.loginUser, name="userLogin"),
    path("login/totp/", views.totp, name="totp"),
    path("register/", views.registerUser, name="userRegister"),
    path("admin/", views.admin, name="admin"), # type: ignore
    path("admin/users/", views.adminUsers, name="adminUsers"), # type: ignore
]

music/models.py
from django.db import models
from users.models import User

class Daina(models.Model):
    class Zanras(models.TextChoices):
        POPMUZIKA = "popmuzika", "Pop muzika"
        ROKAS = "rokas", "Rokas"
        METALAS = "metalas", "Metalas"
        DZIASAS = "dziasas", "Dziazas"
        BLIUZAS = "bliuzas", "Bliuzas"
        KLASIKA = "klasika", "Klasika"
        ELEKTRONIKA = "elektronika", "Elektronika"
        REPAS = "repas", "Repas"
        RNB = "rnb", "R&B"
        KANTRI = "kantri", "Kantri"
        FOLK = "folk", "Folk"
        REGIS = "regis", "Regis"
        ALTERNATYVA = "alternatyva", "Alternatyva"
        DISCO = "disco", "Disco"
        DANCE = "dance", "Dance"
        AMBIENT = "ambient", "Ambient"
        EKSPERIMENTINE = "eksperimentine", "Eksperimentine"
        INSTRUMENTINE = "instrumentine", "Instrumentine"
        OPERA = "opera", "Opera"
        PASAULIO_MUZIKA = "pasaulio_muzika", "Pasaulio muzika"
        TREP = "trep", "Trep"
        TECHNO = "techno", "Techno"
        HOUSE = "house", "House"

    pavadinimas = models.CharField(max_length=255)
    trukme_sekundes = models.IntegerField()
    zanras = models.CharField(choices=Zanras.choices, max_length=50, default=Zanras.POPMUZIKA)
    isleidimo_data = models.DateField(blank=True, null=True)
    paleidimu_kiekis = models.IntegerField(default=0)
    zodziai = models.TextField(blank=True)
    failas_url = models.TextField()
    virselis_url = models.TextField(blank=True)
    aprasymas = models.TextField(blank=True)
    ikelimo_data = models.DateField(auto_now_add=True)
    yra_viesa = models.BooleanField(default=True)
    savininkas = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="dainos"  # Naudotojas.dainos
    )
    def __str__(self):
        return self.pavadinimas


class DainosKlausymas(models.Model):
    daina = models.ForeignKey(Daina, on_delete=models.CASCADE, related_name="klausymai")
    naudotojas = models.ForeignKey(User, on_delete=models.CASCADE, related_name="klausymai")
    trukme_procentais = models.FloatField()
    klausymo_data = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.daina} ({self.klausymo_data})"


class DainosVertinimas(models.Model):
    daina = models.ForeignKey(Daina, on_delete=models.CASCADE, related_name="vertinimai")
    naudotojas = models.ForeignKey(User, on_delete=models.CASCADE, related_name="vertinimai")
    ivertinimas = models.FloatField()
    ivertinimo_data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.daina} - {self.ivertinimas}"

users/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator




class User(models.Model):
    class RoleChoices(models.TextChoices):
        ADMIN = "Admin", "Administratorius"
        REGISTERED = "Registered", "Registruotas naudotojas"

    username = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(5, "Turi būti bent 5 simboliai"),
            MaxLengthValidator(50, "Turi būti ne daugiau nei 50 simbolių"),
        ],
        editable=False
    )
    email = models.EmailField(max_length=254)
    password_hash = models.BinaryField(max_length=60)
    role = models.CharField(max_length=10, choices=RoleChoices, default=RoleChoices.REGISTERED)
    display_name = models.CharField(max_length=50)
    biography = models.TextField(blank=True, null=True)
    profile_cover_url = models.ImageField(blank=True, null=True, upload_to="profile_covers")
    two_factor_enabled = models.BooleanField(default=False)
    two_factor_secret = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    last_login_at = models.DateTimeField(blank=True, null=True)
    is_blocked = models.BooleanField(default=False)
    is_public = models.BooleanField(default=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self) -> str:
        return self.username


class Following(models.Model):
    class FollowingChoices(models.TextChoices):
        ACTIVE = "A", "Sekamas"
        BLOCKED = "B", "Užblokuotas"
        SILENCED = "S", "Nutildytas"
        NOTHING = "N", "Nieko"

    follower = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )
    followed = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="followers"
    )
    date = models.DateTimeField(auto_now=True)
    state = models.CharField(max_length=1, choices=FollowingChoices, default=FollowingChoices.NOTHING)

    def __str__(self) -> str:
        return f"State: {self.state}"

class TwoFaCodeCopy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="twoFaSecrets") 
    code_hash = models.BinaryField(max_length=60)
    time_created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self) -> str:
        return f"User: {self.user.display_name}, Created: {self.time_created}, Code hash: {self.code_hash}"

users/templates/users/admin.html
{% extends "_base.html" %}
{% block title %}Administratorius{% endblock %}
{% block content %}
  <h2 class="mb-4 fw-semibold">Administratorius</h2>
  <p>Čia yra bendras administratoriaus langas.</p>
  <a href="{% url "users:adminUsers" %}">Naudotojai</a>
{% endblock %}

users/templates/users/adminUsers.html
{% extends "_base.html" %}
{% block title %}Naudotojai • Administratorius{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Klaida</h4>
    <ul class="mb-0">
    {% for error in errors %}
        <li>
            {{error}}
        </li>
    {% endfor %}
    </ul>
</div>
{% endif %}
{% if info %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Pranešimas</h4>
    <ul class="mb-0">
    {% for line in info %}
        <li>
            {{line}}
        </li>
    {% endfor %}
    </ul>
</div>
{% endif %}
<h2 class="mb-4 fw-semibold">Naudotojų tvarkyklė</h2>

<table class="table table-bordered table-striped align-middle shadow-sm" style="table-layout: fixed;">
    <colgroup>
        <col style="width: 2.5em;"/>
        <col span="4"/>
        <col style="width: 6.2em;"/>
    </colgroup>
    <thead class="table-dark">
        <tr>
            <th class="text-center">#</th>
            <th>Vardas</th>
            <th>El. paštas</th>
            <th>Rolė</th>
            <th>Užblokuotas</th>
            <th>Veiksmai</th>
        </tr>
    </thead>

    <tbody>
        {% for u in users %}
        <tr>
            <td class="text-center">{{ u.pk }}</td>
            <td>{{ u.display_name|escape }}</td>
            <td>{{ u.email|escape }}</td>
            <td>{{ u.get_role_display }}</td>
            <td>{{ u.is_blocked|yesno:"Taip,Ne" }}</td>
            <td class="text-center">
                {% if u.pk != request.session.user_id %}
                    {% if u.is_blocked %}
                        <button type="submit"
                                title="Atblokuoti"
                                class="btn btn-sm btn-outline-success"
                                name="unblock"
                                value="{{ u.pk }}"
                                form="adminUserForm"
                                onclick="return confirm('Ar tikrai? Naudotojas bus atblokuotas.');">
                                Atblokuoti
                        </button>
                    {% else %}
                        <button type="submit"
                                title="Blokuoti"
                                class="btn btn-sm btn-outline-danger"
                                name="block"
                                value="{{ u.pk }}"
                                form="adminUserForm"
                                onclick="return confirm('Ar tikrai? Naudotojas bus užblokuotas.');">
                                Blokuoti
                        </button>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<form method="post" id="adminUserForm" action="{% url 'users:adminUsers' %}">
    {% csrf_token %}
</form>

{% endblock %}

users/templates/users/edit.html
{% extends "_base.html" %}
{% load static %}
{% block title %}Paskyros redagavimas • Muzikos sistema{% endblock %}

{% block headcontent %}
    <script type="text/javascript" src="{% static "ISPagrindai/javascript/qrcode.min.js" %}"></script>
{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Klaida</h4>
    <ul class="mb-0">
    {% for error in errors %}
        <li>
            {{error}}
        </li>
    {% endfor %}
    </ul>
</div>
{% endif %}
{% if info %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Pranešimas</h4>
    <ul class="mb-0">
    {% for line in info %}
        <li>
            {{line}}
        </li>
    {% endfor %}
    </ul>
</div>
{% endif %}
<h3>{{ user.display_name }} - Paskyros redagavimas</h3>
<form method="post" enctype="multipart/form-data" action="{% url "users:userEdit" %}" name="userform" class="d-grid gap-3 align-items-end">
    {% csrf_token %}
    <div class="">
        <label for="display_name">Rodomas vardas</label>
        <input id="display_name" value="{{ form.display_name }}" class="form-control" type="text" name="display_name" required />
    </div>
    <div class="">
        <label for="email">El. paštas</label>
        <input id="email" value="{{ form.email }}" class="form-control" type="email" name="email" required />
    </div>
    <div class="">
        <label for="biography">Biografija</label>
        <textarea id="biography" class="form-control" type="text" name="biography" rows="3" >{{ form.biography }}</textarea>
    </div>
    <div class="">
        <label for="profile_cover_url">Profilio nuotrauka{% if user.profile_cover_url %} | {{ user.profile_cover_url.name}}{% endif %}</label>
        <input id="profile_cover_url" class="form-control" type="file" accept="image/png, image/jpeg" name="profile_cover_url" />
    </div>
    <!-- <div class="">
        <input id="two_factor_enabled" class="form-check-input" type="checkbox" value="1" name="two_factor_enabled" {{ form.two_factor_enabled|yesno:"checked," }}/>
        <label for="two_factor_enabled" class="form-check-label">Dviejų faktorių autentifikacija</label>
    </div> -->
    <div class="">
        <label for="date_of_birth">Gimimo data</label>
        <input id="date_of_birth" value="{{ form.date_of_birth|default:'' }}" class="form-control" type="date" name="date_of_birth" />
    </div>
    <div class="">
        <input id="is_public" value="1" class="form-check-input" type="checkbox" value="1" name="is_public" {{ form.is_public|yesno:"checked," }} />
        <label for="is_public" class="form-check-label">Matomumas</label>
    </div>
    <div class="row">
        <div class="col-6">
            <input type="button" id="twoFaButton"  
                value='{{ form.two_factor_enabled|yesno:"Išjungti,Įjungti" }} dvejų faktorių autentifikaciją' 
                class="btn btn-outline-primary w-100 me-sm-0 "
            />
        </div>
        <div class="col-6">
            <input type="submit" name="save" value="Išsaugoti" class="btn btn-primary w-100 me-sm-0 "/>
        </div>
    </div>
</form>

<div id="twoFaModal-enable" class="twoFaModal" popover="manual">
    <div class="modal-header">
        <h1 class="modal-title fs-5">Nuskaitykite QR kodą</h1>
        <button type="button" class="btn-close" popovertarget="twoFaModal-enable" popovertargetaction="hide"></button>
    </div>
    <div class="modal-body text-center">
        <p>
            Naudokite autentifikavimo programėlę
            <span class="text-nowrap">
                (Google Authenticator (
                <a href="https://apps.apple.com/us/app/google-authenticator/id388497605" >
                    iOS
                </a>
                /
                <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_US">
                    Android
                </a>
                )
            </span>
            arba
            <span class="text-nowrap">
                Microsoft Authenticator (
                <a href="https://apps.apple.com/us/app/microsoft-authenticator/id983156458">
                    iOS
                </a>
                /
                <a href="https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US">
                    Android
                </a>
                ))
            </span>
            ir įveskite kodą prisijungus prie sistemos. 
        </p>
        <div class="qrcode-container">
            <div id="qrcode" class="placeholder-glow mx-auto"></div>
        </div>
    </div>
</div>

<div id="twoFaModal-disable" class="twoFaModal" popover="manual">
    <div class="modal-header">
        <h1 class="modal-title fs-5">Dviejų faktorių autentifikacija išjungta.</h1>
        <button type="button" class="btn-close" popovertarget="twoFaModal-disable" popovertargetaction="hide"></button>
    </div>
    <div class="modal-body">
        <p>Sėkmingai išjungta dviejų faktorių autentifikacija. Jei norite vėl įjungti 2FA, teks pakartoti QR kodo nuskenavimą.</p>
    </div>
</div>


<script type="text/javascript">
    var qrcode = new QRCode(document.getElementById("qrcode"), {
        width: 300,
        height: 300
    });

    var generated = false;
    var twoFaEnabled = '{{ form.two_factor_enabled|yesno:"true,false" }}' == 'true';

    function enableTwoFa(button) {
        if (generated) return;
        const request = new Request('{% url "users:twoFa" 1 %}');

        fetch(request)
            .then((response) => {
                if (response.status !== 200) {
                    throw new Error("Kažkas ne taip");
                }
                return response.text();
            })
            .then((text) => {
                console.log(text);

                if (text === "") {
                    throw new Error("Nematau response");
                }
                
                qrcode.makeCode(text);
                generated = true;

                modal = document.getElementById("twoFaModal-enable");
                modal.showPopover();

            })
            .catch((error) => {
                console.error(error);
                generated = false;
            });
    }

    function disableTwoFa(button){
        const request = new Request('{% url "users:twoFa" 0 %}');

        fetch(request)
            .then((response) => {
                if (response.status !== 200) {
                    throw new Error("Kažkas ne taip");
                }
                return response.text();
            })
            .then((text) => {
                modal = document.getElementById("twoFaModal-disable");
                modal.showPopover();
            })
            .catch((error) => {
                console.error(error);
            });
    }

    const button = document.getElementById("twoFaButton");

    button.addEventListener('click', (e) => {
        if(twoFaEnabled === false){
            enableTwoFa(e.target);
        }else{
            disableTwoFa(e.target);
        }
        twoFaEnabled = !twoFaEnabled;

        button.value = (twoFaEnabled ? "Išjungti" : "Įjungti") + " dvejų faktorių autentifikaciją";
    })
</script>
{% endblock%}

users/templates/users/index.html
{% extends "_base.html" %}
{% block title %}Naudotojai • Muzikos sistema{% endblock %}
{% block content %}
  <h2 class="mb-4 fw-semibold">Naudotojai</h2>
  <div class="row row-cols-auto g-4">
    {% for user in users %}
    <a class="user-card" href="{% url 'users:userDetail' user.pk %}">
      {% if user.profile_cover_url %}
        <img
          height="180"
          width="180"
          src="{{ user.profile_cover_url.url }}"
          class="rounded-circle shadow-sm"
          alt="user profile cover"
        />
      {% else %}
        <div
        style="width: 180px; height: 180px; box-shadow: inset 0px 0px 16px 0px #000c;"
        class="rounded-circle bg-secondary"
        >
        </div>
      {% endif %}
      <h6 class="card-title mt-1 mb-1">{{ user.display_name }}</h6>
    </a>
    {% endfor %}
  </div>
{% endblock %}

users/templates/users/login.html
{% extends "_base.html" %}
{% block title %}Prisijungimas • Muzikos sistema{% endblock %}
{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Klaida</h4>
    <ul class="mb-0">
    {% for error in errors %}
        <li>
            {{error}}
        </li>
    {% endfor %}
    </ul>
</div>
{% endif %}
<h3>Įveskite savo prisijungimo vardą ir slaptažodį</h3>
<div class="d-flex justify-content-center my-4">
    <form method="post" action="{% url "users:userLogin" %}" name="loginform" class="d-grid gap-3 align-items-end">
        {% csrf_token %}
        <div class="d-flex align-items-sm-center flex-column flex-sm-row gap-2">
            <label for="login_input_username">Prisijungimo vardas</label>
            <input id="login_input_username" value="{{ form.username }}" class="form-control ms-auto" style="width: 16em" type="text" name="username" required />
        </div>
        <div class="d-flex align-items-sm-center flex-column flex-sm-row gap-2">
            <label for="login_input_password">Slaptažodis</label>
            <input id="login_input_password" value="{{ form.password }}" class="form-control ms-auto" style="width: 16em" type="password" name="password" autocomplete="off" required />
        </div>
        <input type="submit" name="login" value="Prisijungti" class="btn btn-primary w-50 mx-auto me-sm-0 "/>
        <input type="hidden" name="next" value="{{ form.next }}">
    </form>
</div>
<p>Jei jungiatės pirmą kartą būtina užsiregistruokite: <a href="{% url "users:userRegister" %}">Registracija</a></p>

{% endblock %}

users/templates/users/userDetail.html
{% extends "_base.html" %}
{% block title %}{{ user.display_name }} • Muzikos sistema{% endblock %}

{% load static %}
{% block headcontent %}
    <script type="text/javascript" src='{% static "ISPagrindai/javascript/player.js" %}'></script>
{% endblock %}

{% block content %}

  {% if info %}
  <div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Pranešimas</h4>
    <ul class="mb-0">
    {% for line in info %}
      <li>
        {{line}}
      </li>
    {% endfor %}
    </ul>
  </div>
  {% endif %}

  <!-- User Header -->
  <div class="card shadow-sm mb-4 bg-body-tertiary">
    <div class="card-body d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center gap-3">
        {% if user.profile_cover_url %}
          <img
            height="180"
            width="180"
            src="{{ user.profile_cover_url.url }}"
            class="rounded-circle shadow-sm"
            alt="user profile cover"
          />
        {% else %}
          <div
            style="width: 180px; height: 180px; box-shadow: inset 0px 0px 16px 0px #000c;"
            class="rounded-circle bg-secondary"
          ></div>
      {% endif %}
        <div>
          <h3 class="mb-1 text-body-emphasis">{{ user.display_name }}</h3>
          <p class="text-muted mb-0">{{ user.follower_count }} sekėjai • {{ user.email }}</p>
          {% if user.biography %}
            <p>{{ user.biography }}</p>
          {% endif %}
        </div>
      </div>
      {% if "user" in request.session %}
        {% if user.pk == request.session.user_id %}
          <a href="{% url 'users:userEdit' %}" class="btn btn-outline-secondary me-2">
            Redaguoti profilį
          </a>
        {% else %}
        <form
          method="post"
          enctype="multipart/form-data"
          action="{% url 'users:userDetail' user.pk %}"
          class="d-flex flex-column gap-2">
          <button type="submit" name="action" value="follow" class="btn btn-outline-secondary me-2">
            Sekti
          </button>
          <button type="submit" name="action" value="block" class="btn btn-outline-secondary me-2">
            Blokuoti
          </button>
          <button type="submit" name="action" value="silance" class="btn btn-outline-secondary me-2">
            Nutildyti
          </button>
          <button type="submit" name="action" value="clear" class="btn btn-outline-secondary me-2">
            Išvalyti
          </button>
        </form>
        {% endif %}
      {% endif %}
    </div>
  </div>

  <section>
    <div class="d-flex justify-content-between align-items-start">
      <h2 class="mb-4 fw-semibold">Dainos</h2>
      {% if "user" in request.session and user.pk == request.session.user_id %}
      <a href="{% url 'music:createSong' %}" class="btn btn-outline-secondary me-2">
        Įkelti dainą
      </a>
      {% endif %}
    </div>
    <div class="row row-cols-auto g-4">
      {% if dainos %}
        {% for daina in dainos %}
          <div class="song-card" data-href="{% url 'music:playSong' daina.pk %}">
            <div class="img-wrapper">
              <img
                height="180"
                width="180"
                src="{{ daina.virselis_url }}"
                class="rounded-2"
                alt="song cover"
              />
              <div class="play-btn-wrapper">
                <span class="tooltip-text">Paleisti {{daina.pavadinimas}}</span>
                <button type="button" class="play-btn" popovertarget="music-player"
                  data-song-id="{{ daina.pk }}"
                  data-audio="{{ daina.failas_url }}"
                  data-title="{{ daina.pavadinimas }}"
                  data-artist="{{ daina.savininkas.display_name }}"
                  data-cover="{{ daina.virselis_url }}"
                >
                  <svg class="play-icon" data-encore-id="icon" role="img" aria-hidden="true" viewBox="0 0 24 24">
                    <path d="m7.05 3.606 13.49 7.788a.7.7 0 0 1 0 1.212L7.05 20.394A.7.7 0 0 1 6 19.788V4.212a.7.7 0 0 1 1.05-.606z"></path>
                  </svg>
                </button>
              </div>
            </div>
            <h6 class="card-title mt-1 mb-1">{{ daina.pavadinimas }}</h6>
            <p class="text-muted small mb-2">{{ daina.savininkas.display_name }}</p>
          </div>
        {% endfor %}
      {% else %}
      <p class="text-muted">Dainų nėra.</p>
      {% endif %}
    </div>
  </section>

  <section>
    <div class="d-flex justify-content-between align-items-start">
      <h2 class="mb-4 fw-semibold">Grojaraščiai</h2>
      {% if "user" in request.session and user.pk == request.session.user_id %}
      <a href="{% url 'playlists:createPlaylist' %}" class="btn btn-outline-secondary me-2">
        Sukurti grojaraštį
      </a>
      {% endif %}
    </div>
    <div class="row row-cols-auto g-4">
      {% if playlists %} 
          {% for playlist in playlists %}
              <a class="playlist-card" href="{% url 'playlists:PlaylistDetail' playlist.pk %}">
                  <img
                      height="180"
                      width="180"
                      src="https://picsum.photos/180?random=5"
                      class="rounded-2"
                      alt="album cover"
                  />
                  <h6 class="card-title mt-1 mb-1">{{ playlist.pavadinimas }}</h6>
              </a>
          {% endfor %} 
      {% else %}
          <p class="text-muted">Grojaraščių nėra.</p>
      {% endif %}
    </div>
  </section>
  
  <section>
    <div class="d-flex justify-content-between align-items-start">
      <h2 class="mb-4 fw-semibold">Koncertai</h2>
      {% if "user" in request.session and user.pk == request.session.user_id %}
      <a href="{% url 'concerts:createConcert' %}" class="btn btn-outline-secondary me-2">
          Skelbti koncertą
        </a>
        {% endif %}
    </div>
    <div class="row g-4">
      {% if koncertai %}
        <div class="col-sm-6 col-md-4 col-lg-3">
          {% for koncertas in koncertai %}
            <a class="card concert-card" href="{% url 'concerts:concertDetail' pk=koncertas.pk %}">
              <img
                src="https://picsum.photos/320/180?random={{ koncertas.pk }}"
                class="card-img-top"
                alt="Concert cover"
              />
              <div class="card-body">
                <small class="text-muted">{% if koncertas.pradzios_data %}{{ koncertas.pradzios_data|date:"Y M d" }}{% endif %} - {% if koncertas.pabaigos_data %}{{ koncertas.pabaigos_data|date:"d" }}{% endif %} · {{ koncertas.get_zanras_display }}</small>
                <h5 class="card-title mt-2">{{ koncertas.pavadinimas }}</h5>
                <small class="text-muted">
                  Bilietų: {{ koncertas.zmoniu_talpa }} · Įvertis: {{ koncertas.rekomendacijos_ivertis|floatformat:1 }}/10
                </small>
                {% if not koncertas.yra_viesas %}
                  <div class="mt-2"><span class="badge bg-secondary">Privatus</span></div>
                {% endif %}
                {% if koncertas.yra_atsauktas %}
                  <div class="mt-2"><span class="badge bg-danger">Atšauktas</span></div>
                {% endif %}
              </div>
            </a>
          {% endfor %}
        </div>
      {% else %}
        <p class="text-muted">Koncertų nėra.</p>
      {% endif %}
    </div>
  </section>
{% endblock %}