ISPagrindai/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("users/", include("users.urls")),
    path("music/", include("music.urls")),
    path("playlists/", include("playlists.urls")),
    path("concerts/", include("concerts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

concerts/urls.py
from django.urls import path, include
from . import views

app_name = "concerts"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createConcert, name="createConcert"),
    path("<int:pk>/edit/", views.editConcert, name="editConcert"),
    path("search/", views.searchConcert, name="searchConcert"),
    path("<int:pk>", views.concertDetail, name="concertDetail"),
    path("recommendation/", views.recommendationConcert, name="recommendationConcert"),
]

music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createSong, name="createSong"),
    path("rate/", views.rateSong, name="rateSong"),
    path("edit/", views.editSong, name="editSong"),
    path("play/<int:song_id>", views.playSong, name="playSong"),
    path("similar/", views.similarSongs, name="similarSongs"),
    path("add/<int:song_id>/", views.addToPlaylist, name="addToPlaylist"),
    path("updateHistory/", views.updateListeningHistory, name="updateHistory")
]

playlists/urls.py
from django.urls import path
from . import views

app_name = "playlists"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createPlaylist, name="createPlaylist"),
    path("<int:pk>/", views.PlaylistDetail, name="PlaylistDetail"),
    path("<int:pk>/edit/", views.editPlaylist, name="editPlaylist"),
    path("<int:pk>/delete/", views.deletePlaylist, name="deletePlaylist"),
    path("<int:grojarastis_id>/remove/<int:song_id>/", views.deleteFromPlaylist, name="deleteFromPlaylist"),
    path("<int:pk>/play/", views.playPlaylistSong, name="playPlaylistSong"),
    path("play/<int:pk>/shuffle/", views.playPlaylistShuffle, name="playPlaylistShuffle"
),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:user_id>/", views.userDetail, name="userDetail"),
    path("edit/", views.userEdit, name="userEdit"),
    path("edit/twoFa/<int:enable>", views.twoFa, name="twoFa"),
    path("logout/", views.logoutUser, name="userLogout"),
    path("login/", views.loginUser, name="userLogin"),
    path("login/totp/", views.totp, name="totp"),
    path("register/", views.registerUser, name="userRegister"),
    path("admin/", views.admin, name="admin"), # type: ignore
    path("admin/users/", views.adminUsers, name="adminUsers"), # type: ignore
]

music/models.py
from django.db import models
from users.models import User

class Daina(models.Model):
    class Zanras(models.TextChoices):
        POPMUZIKA = "popmuzika", "Pop muzika"
        ROKAS = "rokas", "Rokas"
        METALAS = "metalas", "Metalas"
        DZIASAS = "dziasas", "Dziazas"
        BLIUZAS = "bliuzas", "Bliuzas"
        KLASIKA = "klasika", "Klasika"
        ELEKTRONIKA = "elektronika", "Elektronika"
        REPAS = "repas", "Repas"
        RNB = "rnb", "R&B"
        KANTRI = "kantri", "Kantri"
        FOLK = "folk", "Folk"
        REGIS = "regis", "Regis"
        ALTERNATYVA = "alternatyva", "Alternatyva"
        DISCO = "disco", "Disco"
        DANCE = "dance", "Dance"
        AMBIENT = "ambient", "Ambient"
        EKSPERIMENTINE = "eksperimentine", "Eksperimentine"
        INSTRUMENTINE = "instrumentine", "Instrumentine"
        OPERA = "opera", "Opera"
        PASAULIO_MUZIKA = "pasaulio_muzika", "Pasaulio muzika"
        TREP = "trep", "Trep"
        TECHNO = "techno", "Techno"
        HOUSE = "house", "House"

    pavadinimas = models.CharField(max_length=255)
    trukme_sekundes = models.IntegerField()
    zanras = models.CharField(choices=Zanras.choices, max_length=50, default=Zanras.POPMUZIKA)
    isleidimo_data = models.DateField(blank=True, null=True)
    paleidimu_kiekis = models.IntegerField(default=0)
    zodziai = models.TextField(blank=True)
    failas_url = models.TextField()
    virselis_url = models.TextField(blank=True)
    aprasymas = models.TextField(blank=True)
    ikelimo_data = models.DateField(auto_now_add=True)
    yra_viesa = models.BooleanField(default=True)
    savininkas = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="dainos"  # Naudotojas.dainos
    )
    def __str__(self):
        return self.pavadinimas


class DainosKlausymas(models.Model):
    daina = models.ForeignKey(Daina, on_delete=models.CASCADE, related_name="klausymai")
    naudotojas = models.ForeignKey(User, on_delete=models.CASCADE, related_name="klausymai")
    trukme_procentais = models.FloatField()
    klausymo_data = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.daina} ({self.klausymo_data})"


class DainosVertinimas(models.Model):
    daina = models.ForeignKey(Daina, on_delete=models.CASCADE, related_name="vertinimai")
    naudotojas = models.ForeignKey(User, on_delete=models.CASCADE, related_name="vertinimai")
    ivertinimas = models.FloatField()
    ivertinimo_data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.daina} - {self.ivertinimas}"

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
      crossorigin="anonymous"
    ></script>

    <script type="text/javascript" src='{% static "ISPagrindai/javascript/theme.js" %}'></script>
    {% if 'user' in request.session %}
        <script>
            window.user = true;
        </script>
    {% endif %}
    {% block headcontent %}{% endblock %}

    <link rel="stylesheet" href="{% static 'ISPagrindai/css/style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <a class="navbar-brand fw-bold" href="/">Muzikos Sistema</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            {% url 'music:index' as music_index %}
            {% url 'playlists:index' as playlists_index %}
            {% url 'concerts:index' as concerts_index %}
            {% url 'users:index' as users_index %}
            
            <li class="nav-item"><a class="nav-link {% if "/"             == request.path %}active{% endif %}" href="/">Pagrindinis</a></li>
            <li class="nav-item"><a class="nav-link {% if music_index     in request.path %}active{% endif %}" href="{{ music_index }}">Dainos</a></li>
            <li class="nav-item"><a class="nav-link {% if playlists_index in request.path %}active{% endif %}" href="{{ playlists_index }}">Grojaraščiai</a></li>
            <li class="nav-item"><a class="nav-link {% if concerts_index  in request.path %}active{% endif %}" href="{{ concerts_index }}">Koncertai</a></li>
            <li class="nav-item"><a class="nav-link {% if users_index     in request.path %}active{% endif %}" href="{{ users_index }}">Naudotojai</a></li>
            <div class="vr mx-2"></div>
            <li class="nav-item dropdown-center">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                {% if "user_profile_cover_url" in request.session  %}
                  <img src="{{request.session.user_profile_cover_url}}" height="24" width="24" alt="" class="rounded-circle">
                {% else %}
                  <i class="bi bi-person-circle me-1"></i>
                {% endif %}
                {% if "user" in request.session %}
                  {{ request.session.user_display_name }}
                {% endif %}
              </a>
              <ul class="dropdown-menu">
                {% if "user" in request.session  %}
                  <li>
                    <h6 class="dropdown-header">
                      {{ request.session.user_role_label }}
                    </h6>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  {% if request.session.user_role == "Admin" %}
                    <li><a class="dropdown-item" href="{% url 'users:admin' %}">Admin</a></li>
                    <li><hr class="dropdown-divider"></li>
                  {% endif %}
                  <!-- Sekėjai -->
                  {% if fallowers %}
                    <li class="dropstart">
                      <a class="dropdown-item dropdown-toggle" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                        Aš seku
                      </a>
                      <ul class="dropdown-menu dropdown-menu-end">
                        {% for fallowed in fallowers %}
                          <li><a class="dropdown-item" href="{% url 'users:userDetail' fallowed.pk %}">{{ fallowed.display_name }}</a></li>
                        {% endfor %}
                      </ul>
                    </li>
                  {% endif %}
                  <!-- --- -->
                  <li><a class="dropdown-item" href="{% url 'users:userDetail' request.session.user_id %}">Mano profilis</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:userLogout' %}">Atsijungti</a></li>
                {% else %}
                  <li><a class="dropdown-item" href="{% url 'users:userLogin' %}">Prisijungti</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:userRegister' %}">Registruotis</a></li>
                {% endif %}
              </ul>
            </li>
            <div class="vr mx-2"></div>
            <li class="nav-item" style="align-content: center">{% include 'theme-toggle.html' %}</li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="layout">
      <main>
        {% block content_wrapper %}
        <div class="container my-5">
          {% block content %}
          {% endblock %}
        </div>
        {% endblock %}
      </main>

      <footer class="text-white text-center py-4 mt-5">
        <p class="mb-0">2025 • Kaunas</p>
        <small>Informacinių sistemų pagrindai</small>
      </footer>
    </div>
    <div id="music-player" class="music-player" popover="manual">
      <div class="song-info">
        <img src="https://picsum.photos/60?random=50" alt="Album Art" />
        <div>
          <strong>Electric Heart</strong><br />
          <small class="text-muted">DJ Nova</small>
        </div>
      </div>
      <div class="player-controls">
        <audio
          id="music-player-control"
          controls
          controlslist="nodownload"
        ></audio>
      </div>
    </div>
  </body>
</html>

templates/homepage.html
{% extends "_base.html" %}
{% block title %}Muzikos sistema{% endblock %}

{% load static %}
{% block headcontent %}
    <script type="text/javascript" src='{% static "ISPagrindai/javascript/player.js" %}'></script>
{% endblock %}

{% block content %}
  {% if dainos %}
    <h2 class="mb-4 fw-semibold">Populiarios dainos</h2>
    <div class="row row-cols-auto g-4">
      {% for daina in dainos %}
          <div class="song-card" data-href="{% url 'music:playSong' daina.pk %}">
            <div class="img-wrapper">
              <img
                height="180"
                width="180"
                src="{{ daina.virselis_url }}"
                class="rounded-2"
                alt="song cover"
              />
              <div class="play-btn-wrapper">
                <span class="tooltip-text">Paleisti {{daina.pavadinimas}}</span>
                <button type="button" class="play-btn" 
                  popovertarget="music-player"
                  popovertargetaction="show"
                  data-song-id="{{ daina.pk }}"
                  data-audio="{{ daina.failas_url }}"
                  data-title="{{ daina.pavadinimas }}"
                  data-artist="{{ daina.savininkas.display_name }}"
                  data-cover="{{ daina.virselis_url }}"
                >
                  <svg class="play-icon" data-encore-id="icon" role="img" aria-hidden="true" viewBox="0 0 24 24"
                  >
                    <path d="m7.05 3.606 13.49 7.788a.7.7 0 0 1 0 1.212L7.05 20.394A.7.7 0 0 1 6 19.788V4.212a.7.7 0 0 1 1.05-.606z"></path>
                  </svg>
                </button>
              </div>
            </div>
            <h6 class="card-title mt-1 mb-1">{{ daina.pavadinimas }}</h6>
            <p class="text-muted small mb-2">{{ daina.savininkas.display_name }}</p>
          </div>
      {% endfor %}
    </div>
  {% endif %}

  {% if grojarasciai %}
    <h2 class="mt-5 mb-4 fw-semibold">Grojaraščiai</h2>
    <div class="row row-cols-auto g-4">
        {% for grojarastis in grojarasciai %}
            <a class="playlist-card" href="{% url 'playlists:PlaylistDetail' 1 %}">
                <img
                    height="180"
                    width="180"
                    src="https://picsum.photos/180?random=5"
                    class="rounded-2"
                    alt="album cover"
                />
                <h6 class="card-title mt-1 mb-1">{{grojarastis.pavadinimas}}</h6>
                {% if grojarastis.aprasymas %}
                    <p class="text-muted small mb-2">{{ grojarastis.savininkas.display_name }}</p>
                {% endif %}
            </a>
        {% endfor %}
    </div> 
  {% endif %}

  {% if koncertai %}
    <h2 class="mt-5 mb-4 fw-semibold">Būsimi Koncertai</h2>
    <div class="row g-4">
      {% for koncertas in koncertai %}
        <div class="col-sm-6 col-md-4 col-lg-3">
          <a class="card concert-card" href="{% url 'concerts:concertDetail' pk=koncertas.pk %}">
            <img
              src="https://picsum.photos/320/180?random={{ koncertas.pk }}"
              class="card-img-top"
              alt="Concert cover"
            />
            <div class="card-body">
              <small class="text-muted">{% if koncertas.pradzios_data %}{{ koncertas.pradzios_data|date:"Y M d" }}{% endif %} - {% if koncertas.pabaigos_data %}{{ koncertas.pabaigos_data|date:"d" }}{% endif %} · {{ koncertas.get_zanras_display }}</small>
              <h5 class="card-title mt-2">{{ koncertas.pavadinimas }}</h5>
              <small class="text-muted">
                Bilietų: {{ koncertas.zmoniu_talpa }} · Įvertis: {{ koncertas.rekomendacijos_ivertis|floatformat:1 }}/10
              </small>
              {% if not koncertas.yra_viesas %}
                <div class="mt-2"><span class="badge bg-secondary">Privatus</span></div>
              {% endif %}
              {% if koncertas.yra_atsauktas %}
                <div class="mt-2"><span class="badge bg-danger">Atšauktas</span></div>
              {% endif %}
            </div>
          </a>
        </div>
      {% endfor %}
    </div>

  {% endif %}

  {% if users %}
    <h2 class="mt-5 mb-4 fw-semibold">Naudotojai</h2>
    <div class="row row-cols-auto g-4">
      {% for user in users %}
        <a class="user-card" href="{% url 'users:userDetail' user.pk %}">
          {% if user.profile_cover_url %}
            <img
              height="180"
              width="180"
              src="{{ user.profile_cover_url.url }}"
              class="rounded-circle shadow-sm"
              alt="user profile cover"
            />
        {% else %}
            <div
              style="width: 180px; height: 180px; box-shadow: inset 0px 0px 16px 0px #000c;"
              class="rounded-circle"
            ></div>
        {% endif %}
          <h6 class="card-title mt-1 mb-1">{{ user.display_name }}</h6>
        </a>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

templates/theme-toggle.html
<button class="theme-toggle">
  <span class="visually-hidden theme-label-when-auto">Keisti temą (Dabar auto)</span>
  <span class="visually-hidden theme-label-when-light">Keisti temą (Dabar šviesi)</span>
  <span class="visually-hidden theme-label-when-dark">Keisti temą (Dabar tamsi)</span>

  <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-half theme-icon-when-auto" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16"/>
  </svg>
  <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon-stars-fill theme-icon-when-dark" viewBox="0 0 16 16">
    <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278"/>
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.73 1.73 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.73 1.73 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.73 1.73 0 0 0 1.097-1.097zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.16 1.16 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.16 1.16 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732z"/>
  </svg>
  <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sun-fill theme-icon-when-light" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0m0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13m8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5M3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8m10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0m-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0m9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707M4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708"/>
  </svg>
</button>